### ISSUE TITLE
Missing definitions caused by package dependencies not being updated

### ISSUE THREAD

**Issue by miyago9267** [MiraculixxT/MCCommons#1]
In the [bluemap Marker](https://github.com/MiraculixxT/bluemap-marker) plug-in, the latest version of branch relies on version 1.0.1 of mccommon. However, the Maven suite library and github repo have not been updated. When I want to compile, I encounter many problems with undefined functions and templates(Like the picture). Please request the author. Update the suite version or make the old version of bluemap public as another branch.
<img width="750" alt="image" src="https://github.com/user-attachments/assets/1c22b6d5-fa4b-4c2b-9388-0006c8503d6d">

**Comment by MiraculixxT** [comment]
Sorry for this, maven changed some very annoying stuff to proceed updating libs that i didn't performed yet. For now you can clone this repo and execute the gradle task publishToMavenLocal, this makes it available on your machine

**Comment by miyago9267** [comment]
How about the `de.miraculixx:kpaper-light:1.2.1` package?
Like the pictures BMM Paper plugin also depend the unrelease version 1.2.1, but i clone your own repo and look over the source code, its version is 1.2.0 right now.

<img width="812" alt="image" src="https://github.com/user-attachments/assets/37ad4a6a-3c6f-4712-b510-ef0a4428ac9a">

**Comment by MiraculixxT** [comment]
Thanks for the notice. I got my self together today and fixed all maven account migration things and released both updated versions now on mavenCentral. You should be able to reload and fetch gradle in a few minutes (after DNS changes applied)

**Comment by miyago9267** [comment]
Pretty thank, I've seen it on maven central and was able to implement it successfully.
Thank you so much.
